### ISSUE TITLE
[FEAT] SQLite 

### ISSUE THREAD

**Issue by modem7** [linuxserver/docker-hishtory-server#5]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Enable the use of SQLite within the image instead of having to spin up an extra DB container. 

### Reason for change

Ease of use, fewer containers.

### Proposed code change

From https://github.com/ddworken/hishtory#advanced-features

```
A few configuration options:

If you want to use a SQLite backend, you can do so by setting the HISHTORY_SQLITE_DB environment variable to point to a file. It will then create a SQLite DB at the given location.
```

**Comment by thespad** [comment]
Have you tried just setting `HISHTORY_SQLITE_DB` to a path you've mapped to the host? It's a Go app so it should be able to do it without any external deps, but we can always look to add any that turn out to be required.

**Comment by modem7** [comment]
> Have you tried just setting `HISHTORY_SQLITE_DB` to a path you've mapped to the host? It's a Go app so it should be able to do it without any external deps, but we can always look to add any that turn out to be required.

Good shout, I hadn't even considered that......blame the lack of coffee.

It looks like there's an issue upstream, and I've raised it in https://github.com/ddworken/hishtory/issues/128

It merely shows `No database configured, sleeping...` in the logs.

**Comment by Roxedus** [comment]
Thats not a upstream error, thats our doing. https://github.com/linuxserver/docker-hishtory-server/blob/main/root/etc/s6-overlay/s6-rc.d/init-hishtory-config/run#L8

**Comment by thespad** [comment]
I can fix that easily enough

**Comment by thespad** [comment]
Can you test with `ghcr.io/linuxserver/lspipepr-hishtory-server:v0.251-pkg-fb5a6151-dev-7cd680f8c28ab4699e98ac8c8232432366fba732-pr-6` and see if that works for you.

**Comment by modem7** [comment]
Whehei!

Looks like we're good!

```console
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    999
───────────────────────────────────────

Using SQLite database, ensure you have mounted /squite/hishtory.sqlite into the container
[custom-init] No custom files found, skipping...
Opening DB
Connecting to DB
AutoMigrating DB tables
Pinging DB to confirm liveness
Done initializing DB
Listening on :8080
UnknownIp GET "/healthcheck"  13.904µs 2 B
[ls.io-init] done.
Found a valid version: v0.251
```

```yaml
  hishtory-server:
    #image: lscr.io/linuxserver/hishtory-server:latest
    image: ghcr.io/linuxserver/lspipepr-hishtory-server:v0.251-pkg-fb5a6151-dev-7cd680f8c28ab4699e98ac8c8232432366fba732-pr-6
    container_name: Hishtory-Server
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - HISHTORY_SQLITE_DB=/squite/hishtory.sqlite
      # - HISHTORY_POSTGRES_DB=postgresql://${HISHTORY_DB_USER}:${HISHTORY_DB_PASS}@localhost:5432/hishtory?sslmode=disable
    network_mode: "host"
    volumes:
      - $USERDIR/HishtoryDB:/squite
#    ports:
#      - 24244:8080
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    # depends_on:
      # - hishtory-db
    restart: always
```
